// Nepal Provinces and Districts Data
export const nepalProvinces = [
    { id: '1', name: 'प्रदेश नं. १', nameEn: 'Province No. 1' },
    { id: '2', name: 'मधेश प्रदेश', nameEn: 'Madhesh Province' },
    { id: '3', name: 'बागमती प्रदेश', nameEn: 'Bagmati Province' },
    { id: '4', name: 'गण्डकी प्रदेश', nameEn: 'Gandaki Province' },
    { id: '5', name: 'लुम्बिनी प्रदेश', nameEn: 'Lumbini Province' },
    { id: '6', name: 'कर्णाली प्रदेश', nameEn: 'Karnali Province' },
    { id: '7', name: 'सुदूरपश्चिम प्रदेश', nameEn: 'Sudurpashchim Province' },
];

export const nepalDistricts: { [key: string]: { id: string; name: string }[] } = {
    '1': [
        { id: 'bhojpur', name: 'भोजपुर' },
        { id: 'dhankuta', name: 'धनकुटा' },
        { id: 'ilam', name: 'इलाम' },
        { id: 'jhapa', name: 'झापा' },
        { id: 'khotang', name: 'खोटाङ' },
        { id: 'morang', name: 'मोरङ' },
        { id: 'okhaldhunga', name: 'ओखलढुङ्गा' },
        { id: 'panchthar', name: 'पाँचथर' },
        { id: 'sankhuwasabha', name: 'संखुवासभा' },
        { id: 'solukhumbu', name: 'सोलुखुम्बु' },
        { id: 'sunsari', name: 'सुनसरी' },
        { id: 'taplejung', name: 'ताप्लेजुङ' },
        { id: 'terhathum', name: 'तेह्रथुम' },
        { id: 'udayapur', name: 'उदयपुर' },
    ],
    '2': [
        { id: 'bara', name: 'बारा' },
        { id: 'dhanusha', name: 'धनुषा' },
        { id: 'mahottari', name: 'महोत्तरी' },
        { id: 'parsa', name: 'पर्सा' },
        { id: 'rautahat', name: 'रौतहट' },
        { id: 'saptari', name: 'सप्तरी' },
        { id: 'sarlahi', name: 'सर्लाही' },
        { id: 'siraha', name: 'सिराहा' },
    ],
    '3': [
        { id: 'bhaktapur', name: 'भक्तपुर' },
        { id: 'chitwan', name: 'चितवन' },
        { id: 'dhading', name: 'धादिङ' },
        { id: 'dolakha', name: 'दोलखा' },
        { id: 'kathmandu', name: 'काठमाडौं' },
        { id: 'kavrepalanchok', name: 'काभ्रेपलाञ्चोक' },
        { id: 'lalitpur', name: 'ललितपुर' },
        { id: 'makwanpur', name: 'मकवानपुर' },
        { id: 'nuwakot', name: 'नुवाकोट' },
        { id: 'ramechhap', name: 'रामेछाप' },
        { id: 'rasuwa', name: 'रसुवा' },
        { id: 'sindhuli', name: 'सिन्धुली' },
        { id: 'sindhupalchok', name: 'सिन्धुपाल्चोक' },
    ],
    '4': [
        { id: 'baglung', name: 'बाग्लुङ' },
        { id: 'gorkha', name: 'गोरखा' },
        { id: 'kaski', name: 'कास्की' },
        { id: 'lamjung', name: 'लम्जुङ' },
        { id: 'manang', name: 'मनाङ' },
        { id: 'mustang', name: 'मुस्ताङ' },
        { id: 'myagdi', name: 'म्याग्दी' },
        { id: 'nawalpur', name: 'नवलपुर' },
        { id: 'parbat', name: 'पर्वत' },
        { id: 'syangja', name: 'स्याङ्जा' },
        { id: 'tanahun', name: 'तनहुँ' },
    ],
    '5': [
        { id: 'arghakhanchi', name: 'अर्घाखाँची' },
        { id: 'banke', name: 'बाँके' },
        { id: 'bardiya', name: 'बर्दिया' },
        { id: 'dang', name: 'दाङ' },
        { id: 'gulmi', name: 'गुल्मी' },
        { id: 'kapilvastu', name: 'कपिलवस्तु' },
        { id: 'nawalparasi_west', name: 'नवलपरासी (बर्दघाट सुस्ता पश्चिम)' },
        { id: 'palpa', name: 'पाल्पा' },
        { id: 'pyuthan', name: 'प्युठान' },
        { id: 'rolpa', name: 'रोल्पा' },
        { id: 'rupandehi', name: 'रुपन्देही' },
        { id: 'eastern_rukum', name: 'पूर्वी रुकुम' },
    ],
    '6': [
        { id: 'dailekh', name: 'दैलेख' },
        { id: 'dolpa', name: 'डोल्पा' },
        { id: 'humla', name: 'हुम्ला' },
        { id: 'jajarkot', name: 'जाजरकोट' },
        { id: 'jumla', name: 'जुम्ला' },
        { id: 'kalikot', name: 'कालिकोट' },
        { id: 'mugu', name: 'मुगु' },
        { id: 'salyan', name: 'सल्यान' },
        { id: 'surkhet', name: 'सुर्खेत' },
        { id: 'western_rukum', name: 'पश्चिमी रुकुम' },
    ],
    '7': [
        { id: 'achham', name: 'अछाम' },
        { id: 'baitadi', name: 'बैतडी' },
        { id: 'bajhang', name: 'बझाङ' },
        { id: 'bajura', name: 'बाजुरा' },
        { id: 'dadeldhura', name: 'डडेलधुरा' },
        { id: 'darchula', name: 'दार्चुला' },
        { id: 'doti', name: 'डोटी' },
        { id: 'kailali', name: 'कैलाली' },
        { id: 'kanchanpur', name: 'कञ्चनपुर' },
    ],
};

export const getDistrictsByProvince = (provinceId: string) => {
    return nepalDistricts[provinceId] || [];
};
